// Career Compass — sector intelligence data
// Curated from US Census Bureau BFS data and NAICS sector analysis
// Maps business sectors → AI-augmented roles → GiveLedger training modules

export type GrowthLevel = "Very High" | "High" | "Growing" | "Steady";

export interface SectorRole {
  title: string;
  description: string; // how AI makes this role accessible without prior specialism
  aiTools: string[];
  trainingSlug: string;
  trainingTitle: string;
}

export interface Sector {
  id: string;
  name: string;
  emoji: string;
  description: string;
  naics: string;
  growthLevel: GrowthLevel;
  growthPct: string;       // e.g. "+16% YoY" — sourced from BFS
  jobsLabel: string;       // e.g. "60k+ new roles/yr"
  topAiTools: string[];    // top 3 for card display
  roles: SectorRole[];
}

export const SECTORS: Sector[] = [
  {
    id: "technology-software",
    name: "Technology & Software",
    emoji: "💻",
    description: "SaaS companies, startups, and digital product teams hiring AI-fluent generalists for ops, support, research, and documentation.",
    naics: "51, 54",
    growthLevel: "Very High",
    growthPct: "+18% YoY",
    jobsLabel: "80k+ new roles/yr",
    topAiTools: ["Claude", "GitHub Copilot", "ChatGPT"],
    roles: [
      {
        title: "Technical Documentation Writer",
        description: "AI can draft, structure, and format technical docs from rough notes. No engineering background needed — just clarity and good prompting.",
        aiTools: ["Claude", "Notion AI", "ChatGPT"],
        trainingSlug: "product-technology",
        trainingTitle: "Product & Technology Workflows",
      },
      {
        title: "QA / Testing Analyst",
        description: "AI generates test cases, writes bug reports from descriptions, and helps triage issue backlogs. Logical thinking > coding knowledge.",
        aiTools: ["ChatGPT", "Claude", "GitHub Copilot"],
        trainingSlug: "product-technology",
        trainingTitle: "Product & Technology Workflows",
      },
      {
        title: "Product Research Analyst",
        description: "Synthesise competitor research, user feedback, and market data using AI. Companies need this constantly — few have dedicated staff.",
        aiTools: ["Perplexity", "Claude", "ChatGPT"],
        trainingSlug: "data-impact-measurement",
        trainingTitle: "Data & Impact Measurement",
      },
      {
        title: "Customer Success Coordinator",
        description: "AI drafts responses, summarises support tickets, and identifies patterns in feedback. High-volume role, perfect for AI-augmented generalists.",
        aiTools: ["Claude", "ChatGPT", "Intercom AI"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Community & Developer Relations",
        description: "Write newsletters, moderate forums, curate digests, and respond to community questions — all areas where AI dramatically speeds up output.",
        aiTools: ["Claude", "ChatGPT", "Notion AI"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
    ],
  },
  {
    id: "marketing-advertising",
    name: "Marketing & Advertising",
    emoji: "📣",
    description: "Agencies, in-house marketing teams, and DTC brands need AI-fluent content producers, researchers, and coordinators at scale.",
    naics: "54",
    growthLevel: "High",
    growthPct: "+13% YoY",
    jobsLabel: "55k+ new roles/yr",
    topAiTools: ["Claude", "ChatGPT", "Jasper"],
    roles: [
      {
        title: "Content Strategist",
        description: "AI can draft, edit, and repurpose content at scale. Your job is strategy, brand voice guidance, and quality review — not manual writing.",
        aiTools: ["Claude", "ChatGPT", "Jasper"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "Social Media Manager",
        description: "AI generates caption variants, hashtag sets, and posting calendars from a brief. You direct, curate, and engage — not create from scratch.",
        aiTools: ["Claude", "ChatGPT", "Canva AI"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "SEO Content Analyst",
        description: "AI conducts keyword research, writes meta descriptions, and optimises existing copy. Basic SEO understanding + strong prompting = value.",
        aiTools: ["ChatGPT", "Perplexity", "SurferSEO"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "Email Campaign Coordinator",
        description: "AI drafts full email sequences, subject line variants, and A/B test copy from a product brief. Huge demand, low supply of skilled coordinators.",
        aiTools: ["Claude", "ChatGPT", "Mailchimp AI"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "Market Research Analyst",
        description: "AI synthesises industry reports, competitor analysis, and customer sentiment. Turn raw data into actionable insights without an economics degree.",
        aiTools: ["Perplexity", "Claude", "ChatGPT"],
        trainingSlug: "data-impact-measurement",
        trainingTitle: "Data & Impact Measurement",
      },
    ],
  },
  {
    id: "professional-services",
    name: "Professional Services",
    emoji: "🏢",
    description: "Consulting firms, management agencies, and professional practices hiring AI-fluent coordinators, researchers, and proposal writers.",
    naics: "54",
    growthLevel: "High",
    growthPct: "+11% YoY",
    jobsLabel: "45k+ new roles/yr",
    topAiTools: ["Claude", "ChatGPT", "Perplexity"],
    roles: [
      {
        title: "Proposal & Bid Writer",
        description: "AI drafts RFP responses, capability statements, and project summaries from templates and past work. High demand at agencies of every size.",
        aiTools: ["Claude", "ChatGPT", "Notion AI"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Research & Insights Analyst",
        description: "Synthesise market reports, client background research, and industry analysis using AI. Consultants need this work done constantly.",
        aiTools: ["Perplexity", "Claude", "ChatGPT"],
        trainingSlug: "data-impact-measurement",
        trainingTitle: "Data & Impact Measurement",
      },
      {
        title: "Project Coordinator",
        description: "AI drafts status reports, action logs, meeting summaries, and timeline documentation. Coordination + clear communication = the whole job.",
        aiTools: ["Claude", "Notion AI", "ChatGPT"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Client Reporting Specialist",
        description: "Turn raw data and metrics into polished client-facing reports using AI. Analytical thinking + good formatting instincts > specialist training.",
        aiTools: ["Claude", "ChatGPT", "Microsoft Copilot"],
        trainingSlug: "data-impact-measurement",
        trainingTitle: "Data & Impact Measurement",
      },
      {
        title: "Process Documentation Writer",
        description: "AI turns messy process notes into structured SOPs, how-to guides, and training materials. Every growing firm needs this — few prioritise it.",
        aiTools: ["Claude", "Notion AI", "ChatGPT"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
    ],
  },
  {
    id: "financial-services",
    name: "Financial Services & Fintech",
    emoji: "💰",
    description: "Banks, fintechs, accounting firms, and investment companies hiring AI-fluent analysts, compliance coordinators, and communications specialists.",
    naics: "52",
    growthLevel: "High",
    growthPct: "+14% YoY",
    jobsLabel: "40k+ new roles/yr",
    topAiTools: ["Claude", "ChatGPT", "Microsoft Copilot"],
    roles: [
      {
        title: "Financial Data Analyst",
        description: "AI interprets financial statements, generates commentary, and structures reports from data dumps. Analytical thinking > CFA.",
        aiTools: ["Claude", "ChatGPT", "Microsoft Copilot"],
        trainingSlug: "finance-workflows",
        trainingTitle: "Finance & Accounting Workflows",
      },
      {
        title: "Compliance Documentation Specialist",
        description: "AI drafts policy documents, regulatory summaries, and compliance checklists from source materials. High demand, hard to fill.",
        aiTools: ["Claude", "Perplexity", "ChatGPT"],
        trainingSlug: "legal-compliance-workflows",
        trainingTitle: "Legal & Compliance Workflows",
      },
      {
        title: "Customer Communications Coordinator",
        description: "AI writes account notices, product updates, and support responses at scale. Financial tone + compliance awareness + good prompting.",
        aiTools: ["Claude", "ChatGPT", "Intercom AI"],
        trainingSlug: "finance-workflows",
        trainingTitle: "Finance & Accounting Workflows",
      },
      {
        title: "Bookkeeping Support Analyst",
        description: "AI categorises transactions, prepares reconciliation summaries, and drafts bookkeeping notes from bank statements. QuickBooks experience a plus but not required.",
        aiTools: ["Claude", "ChatGPT", "Microsoft Copilot"],
        trainingSlug: "finance-workflows",
        trainingTitle: "Finance & Accounting Workflows",
      },
      {
        title: "Investment Research Coordinator",
        description: "Summarise analyst reports, earnings calls, and SEC filings using AI. Fintech and VC firms need this constantly — junior research support is chronically understaffed.",
        aiTools: ["Perplexity", "Claude", "ChatGPT"],
        trainingSlug: "data-impact-measurement",
        trainingTitle: "Data & Impact Measurement",
      },
    ],
  },
  {
    id: "healthcare-wellness",
    name: "Healthcare & Wellness",
    emoji: "🏥",
    description: "Clinics, health tech platforms, and wellness companies hiring AI-fluent writers, coordinators, and administrative support at high volume.",
    naics: "62",
    growthLevel: "Very High",
    growthPct: "+16% YoY",
    jobsLabel: "90k+ new roles/yr",
    topAiTools: ["Claude", "ChatGPT", "Perplexity"],
    roles: [
      {
        title: "Health Content Writer",
        description: "AI drafts patient education materials, blog posts, and health guides from clinical briefs. Strong AI output + human accuracy review = the workflow.",
        aiTools: ["Claude", "ChatGPT", "Perplexity"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "Medical Documentation Assistant",
        description: "AI formats clinical notes, transcribes encounter summaries, and structures reports. Growing area as EHR platforms adopt AI features.",
        aiTools: ["Claude", "ChatGPT", "Nuance DAX"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Patient Communications Coordinator",
        description: "Draft appointment reminders, follow-up instructions, and intake surveys using AI. Empathy + clarity + good prompting > clinical training.",
        aiTools: ["Claude", "ChatGPT", "Intercom AI"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Healthcare Research Summariser",
        description: "Condense clinical studies, industry reports, and regulatory updates into plain-language summaries for non-clinical audiences. High demand from health tech companies.",
        aiTools: ["Perplexity", "Claude", "ChatGPT"],
        trainingSlug: "data-impact-measurement",
        trainingTitle: "Data & Impact Measurement",
      },
      {
        title: "Administrative Operations Coordinator",
        description: "AI drafts SOPs, schedules, and operational documentation. Healthcare admin is chronically understaffed — AI-fluent coordinators are in high demand.",
        aiTools: ["Claude", "Notion AI", "ChatGPT"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
    ],
  },
  {
    id: "ecommerce-retail",
    name: "E-commerce & Retail",
    emoji: "🛒",
    description: "Online retailers, DTC brands, and marketplace sellers needing AI-fluent operators for content, support, and operations at scale.",
    naics: "44–45",
    growthLevel: "Growing",
    growthPct: "+9% YoY",
    jobsLabel: "35k+ new roles/yr",
    topAiTools: ["ChatGPT", "Claude", "Jasper"],
    roles: [
      {
        title: "Product Description Writer",
        description: "AI generates product copy, bullet points, and SEO titles in bulk from specs. Brands with 1,000+ SKUs have a permanent backlog of this work.",
        aiTools: ["ChatGPT", "Claude", "Jasper"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "Customer Support Specialist",
        description: "AI drafts responses, flags escalations, and handles common queries. Human empathy + AI speed = the winning combination for ecom support.",
        aiTools: ["Claude", "ChatGPT", "Gorgias AI"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Order Operations Coordinator",
        description: "Track fulfilment issues, coordinate with 3PL providers, and manage exceptions using AI to draft communications and summarise issues.",
        aiTools: ["Claude", "ChatGPT", "Notion AI"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Returns & Refunds Analyst",
        description: "AI identifies return patterns, drafts policy responses, and summarises customer feedback. High-volume, structured work — ideal for AI augmentation.",
        aiTools: ["Claude", "ChatGPT", "Perplexity"],
        trainingSlug: "data-impact-measurement",
        trainingTitle: "Data & Impact Measurement",
      },
      {
        title: "Marketplace Listing Coordinator",
        description: "Optimise Amazon/Etsy/Walmart listings using AI to rewrite titles, bullets, and A+ content. Massive opportunity for freelancers and part-time workers.",
        aiTools: ["ChatGPT", "Claude", "Jasper"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
    ],
  },
  {
    id: "legal-services",
    name: "Legal Services",
    emoji: "⚖️",
    description: "Law firms, legal tech platforms, and compliance teams hiring AI-fluent researchers, document analysts, and client communications specialists.",
    naics: "54",
    growthLevel: "Growing",
    growthPct: "+8% YoY",
    jobsLabel: "25k+ new roles/yr",
    topAiTools: ["Claude", "Perplexity", "Harvey AI"],
    roles: [
      {
        title: "Legal Research Assistant",
        description: "AI finds cases, summarises statutes, and drafts research memos from a brief. Legal research fluency + AI prompting > paralegal certification for many firms.",
        aiTools: ["Perplexity", "Claude", "Harvey AI"],
        trainingSlug: "legal-compliance-workflows",
        trainingTitle: "Legal & Compliance Workflows",
      },
      {
        title: "Document Review & Summariser",
        description: "AI summarises lengthy contracts, NDAs, and discovery documents into plain-language summaries. High-volume firms outsource this constantly.",
        aiTools: ["Claude", "ChatGPT", "Harvey AI"],
        trainingSlug: "legal-compliance-workflows",
        trainingTitle: "Legal & Compliance Workflows",
      },
      {
        title: "Compliance Tracking Coordinator",
        description: "Monitor regulatory changes, update compliance calendars, and draft policy summaries using AI. Fintech and healthcare legal teams especially need this.",
        aiTools: ["Claude", "Perplexity", "ChatGPT"],
        trainingSlug: "legal-compliance-workflows",
        trainingTitle: "Legal & Compliance Workflows",
      },
      {
        title: "Client Intake & Communications Specialist",
        description: "Draft client intake questionnaires, status update emails, and engagement letters using AI templates. Clear writing + legal awareness > law degree.",
        aiTools: ["Claude", "ChatGPT", "Notion AI"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Contract Data Extraction Analyst",
        description: "AI extracts key terms, dates, and obligations from contract repositories into structured databases. Contract management platforms are building this capability.",
        aiTools: ["Claude", "ChatGPT", "Harvey AI"],
        trainingSlug: "data-impact-measurement",
        trainingTitle: "Data & Impact Measurement",
      },
    ],
  },
  {
    id: "education-edtech",
    name: "Education & EdTech",
    emoji: "🎓",
    description: "Schools, universities, online learning platforms, and corporate training companies building AI-native learning experiences.",
    naics: "61",
    growthLevel: "Growing",
    growthPct: "+11% YoY",
    jobsLabel: "30k+ new roles/yr",
    topAiTools: ["Claude", "ChatGPT", "Canva AI"],
    roles: [
      {
        title: "Curriculum Content Writer",
        description: "AI drafts lesson outlines, learning materials, and course scripts from subject briefs. EdTech platforms have massive content backlogs — this role is always open.",
        aiTools: ["Claude", "ChatGPT", "Canva AI"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "Learning Materials Coordinator",
        description: "Format, structure, and QA learning content across platforms. AI speeds up formatting and consistency checks — organisational instincts + attention to detail.",
        aiTools: ["Claude", "Notion AI", "ChatGPT"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Student Support Specialist",
        description: "AI drafts responses to common student enquiries, summarises advisor notes, and escalates edge cases. High-volume support role increasingly AI-assisted.",
        aiTools: ["Claude", "ChatGPT", "Intercom AI"],
        trainingSlug: "hr-people-workflows",
        trainingTitle: "HR & People Operations Workflows",
      },
      {
        title: "Assessment & Quiz Creator",
        description: "AI generates multiple-choice questions, scenario-based assessments, and answer keys from learning objectives. Every educator needs this — few have time.",
        aiTools: ["Claude", "ChatGPT", "Canva AI"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "Instructional Design Coordinator",
        description: "Structure learning paths, map competencies to content, and draft storyboards for e-learning using AI. Growing rapidly as corporate L&D goes digital.",
        aiTools: ["Claude", "ChatGPT", "Notion AI"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
    ],
  },
  {
    id: "real-estate-proptech",
    name: "Real Estate & PropTech",
    emoji: "🏠",
    description: "Property management firms, real estate agencies, and PropTech platforms hiring AI-fluent writers, analysts, and coordinators.",
    naics: "53",
    growthLevel: "Growing",
    growthPct: "+9% YoY",
    jobsLabel: "28k+ new roles/yr",
    topAiTools: ["Claude", "ChatGPT", "Perplexity"],
    roles: [
      {
        title: "Property Listing Writer",
        description: "AI generates compelling listing descriptions, virtual tour scripts, and neighbourhood profiles from property specs and photos. High volume, low time per listing.",
        aiTools: ["Claude", "ChatGPT", "Jasper"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "Market Research Analyst",
        description: "AI synthesises comparable sales data, market trend reports, and neighbourhood analyses. Agents and investors need this constantly — few have dedicated analysts.",
        aiTools: ["Perplexity", "Claude", "ChatGPT"],
        trainingSlug: "data-impact-measurement",
        trainingTitle: "Data & Impact Measurement",
      },
      {
        title: "Client Communications Coordinator",
        description: "Draft buyer/seller update emails, offer summaries, and closing checklists using AI. Transaction coordination is a growing specialisation in busy markets.",
        aiTools: ["Claude", "ChatGPT", "Notion AI"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Lease Documentation Specialist",
        description: "Format, review, and summarise lease agreements using AI. Property management companies process hundreds of leases — this role has permanent demand.",
        aiTools: ["Claude", "ChatGPT", "Harvey AI"],
        trainingSlug: "legal-compliance-workflows",
        trainingTitle: "Legal & Compliance Workflows",
      },
      {
        title: "Social Media & Marketing Coordinator",
        description: "Manage property social accounts, create listing campaigns, and produce short-form content using AI. Every agency needs this but most agents do it poorly.",
        aiTools: ["Claude", "Canva AI", "ChatGPT"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
    ],
  },
  {
    id: "hr-recruitment",
    name: "HR & Recruitment",
    emoji: "👥",
    description: "HR departments, staffing agencies, and people-first platforms hiring AI-fluent coordinators for talent acquisition, onboarding, and communications.",
    naics: "56",
    growthLevel: "Steady",
    growthPct: "+7% YoY",
    jobsLabel: "22k+ new roles/yr",
    topAiTools: ["Claude", "ChatGPT", "Microsoft Copilot"],
    roles: [
      {
        title: "Job Description Writer",
        description: "AI writes job descriptions, inclusive language variants, and LinkedIn posts from a brief. Recruiting teams post dozens of roles a month — this backlog never clears itself.",
        aiTools: ["Claude", "ChatGPT", "Textio"],
        trainingSlug: "hr-people-workflows",
        trainingTitle: "HR & People Operations Workflows",
      },
      {
        title: "Candidate Screening Coordinator",
        description: "AI summarises candidate profiles against job criteria and drafts screening question sets. Reduces hours of manual review to minutes with the right prompting.",
        aiTools: ["Claude", "ChatGPT", "Microsoft Copilot"],
        trainingSlug: "hr-people-workflows",
        trainingTitle: "HR & People Operations Workflows",
      },
      {
        title: "Onboarding Programme Coordinator",
        description: "Build onboarding checklists, first-day guides, and 30/60/90 day plans using AI. High-impact role — good onboarding directly reduces early attrition.",
        aiTools: ["Claude", "Notion AI", "ChatGPT"],
        trainingSlug: "hr-people-workflows",
        trainingTitle: "HR & People Operations Workflows",
      },
      {
        title: "HR Documentation Specialist",
        description: "Draft policies, employee handbooks, and compliance documentation using AI. Growing companies update these constantly — few have dedicated resource.",
        aiTools: ["Claude", "ChatGPT", "Microsoft Copilot"],
        trainingSlug: "hr-people-workflows",
        trainingTitle: "HR & People Operations Workflows",
      },
      {
        title: "Employee Communications Writer",
        description: "AI drafts all-hands announcements, policy updates, and culture communications. Internal comms is chronically underfunded — AI makes one person very productive.",
        aiTools: ["Claude", "ChatGPT", "Notion AI"],
        trainingSlug: "hr-people-workflows",
        trainingTitle: "HR & People Operations Workflows",
      },
    ],
  },
  {
    id: "logistics-supply-chain",
    name: "Logistics & Supply Chain",
    emoji: "🚚",
    description: "3PLs, freight brokers, e-commerce fulfilment, and manufacturing support hiring AI-fluent coordinators and operations analysts.",
    naics: "48–49",
    growthLevel: "Growing",
    growthPct: "+10% YoY",
    jobsLabel: "32k+ new roles/yr",
    topAiTools: ["Claude", "ChatGPT", "Perplexity"],
    roles: [
      {
        title: "Operations & Dispatch Coordinator",
        description: "AI drafts carrier communications, exception reports, and route summaries from operational data. High-volume, deadline-driven — AI makes one coordinator do the work of three.",
        aiTools: ["Claude", "ChatGPT", "Notion AI"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Vendor Communications Specialist",
        description: "Draft supplier RFQs, performance reviews, and onboarding documents using AI. Supply chain teams spend disproportionate time on routine vendor correspondence.",
        aiTools: ["Claude", "ChatGPT", "Perplexity"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Freight Documentation Analyst",
        description: "Prepare bills of lading, customs summaries, and shipment documentation using AI. Compliance-heavy, high-volume — AI dramatically reduces error rates.",
        aiTools: ["Claude", "ChatGPT", "Microsoft Copilot"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
      {
        title: "Supply Chain Data Coordinator",
        description: "Compile, clean, and summarise inventory, lead time, and cost data using AI. Analytics instinct + good prompting > supply chain degree for coordinator roles.",
        aiTools: ["Claude", "ChatGPT", "Microsoft Copilot"],
        trainingSlug: "data-impact-measurement",
        trainingTitle: "Data & Impact Measurement",
      },
      {
        title: "Process Improvement Writer",
        description: "Document operational procedures, exception playbooks, and training guides using AI. Every warehouse and 3PL is chronically short of good SOPs.",
        aiTools: ["Claude", "Notion AI", "ChatGPT"],
        trainingSlug: "operations-workflows",
        trainingTitle: "Operations & Project Workflows",
      },
    ],
  },
  {
    id: "media-content",
    name: "Media & Content Production",
    emoji: "🎬",
    description: "Publishers, podcasters, newsletters, and content studios scaling output with AI-fluent editors, researchers, and production coordinators.",
    naics: "51",
    growthLevel: "High",
    growthPct: "+12% YoY",
    jobsLabel: "38k+ new roles/yr",
    topAiTools: ["Claude", "ChatGPT", "ElevenLabs"],
    roles: [
      {
        title: "Research & Script Writer",
        description: "AI researches topics, structures episode outlines, and drafts scripts from source material. Podcast and video studios need this at scale.",
        aiTools: ["Claude", "ChatGPT", "Perplexity"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "Content Repurposing Specialist",
        description: "Turn a long-form piece into short clips, social posts, newsletter sections, and quotes using AI. One piece of content → 20 assets. High value, repeatable work.",
        aiTools: ["Claude", "ChatGPT", "Descript"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "Newsletter Editor",
        description: "Curate, summarise, and write newsletter issues using AI research and drafting. Solo newsletter operators and media companies both need this constantly.",
        aiTools: ["Claude", "ChatGPT", "Perplexity"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "Podcast Production Coordinator",
        description: "AI generates show notes, transcripts, chapter markers, and social clips from recordings. Production companies produce 50+ episodes a month — this is never fully staffed.",
        aiTools: ["Claude", "Descript", "ElevenLabs"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
      {
        title: "Social Content Planner",
        description: "Build content calendars, draft post variants, and manage asset libraries using AI. Every media brand needs this — most are understaffed relative to publishing volume.",
        aiTools: ["Claude", "ChatGPT", "Canva AI"],
        trainingSlug: "marketing-workflows",
        trainingTitle: "Marketing & Content Workflows",
      },
    ],
  },
];

// State → featured sector IDs (based on US Census BFS regional business formation data)
export const STATE_SECTORS: Record<string, string[]> = {
  CA: ["technology-software", "marketing-advertising", "media-content", "ecommerce-retail"],
  TX: ["technology-software", "healthcare-wellness", "real-estate-proptech", "professional-services"],
  FL: ["healthcare-wellness", "real-estate-proptech", "ecommerce-retail", "logistics-supply-chain"],
  NY: ["financial-services", "legal-services", "media-content", "marketing-advertising"],
  IL: ["technology-software", "financial-services", "logistics-supply-chain", "hr-recruitment"],
  PA: ["healthcare-wellness", "financial-services", "education-edtech", "professional-services"],
  OH: ["healthcare-wellness", "professional-services", "logistics-supply-chain", "hr-recruitment"],
  GA: ["technology-software", "logistics-supply-chain", "marketing-advertising", "healthcare-wellness"],
  WA: ["technology-software", "ecommerce-retail", "professional-services", "media-content"],
  MA: ["technology-software", "healthcare-wellness", "financial-services", "education-edtech"],
  NC: ["technology-software", "healthcare-wellness", "professional-services", "financial-services"],
  MI: ["logistics-supply-chain", "healthcare-wellness", "professional-services", "hr-recruitment"],
  NJ: ["financial-services", "healthcare-wellness", "legal-services", "professional-services"],
  VA: ["technology-software", "professional-services", "legal-services", "hr-recruitment"],
  AZ: ["real-estate-proptech", "technology-software", "healthcare-wellness", "ecommerce-retail"],
  CO: ["technology-software", "real-estate-proptech", "marketing-advertising", "education-edtech"],
  TN: ["healthcare-wellness", "logistics-supply-chain", "ecommerce-retail", "hr-recruitment"],
  IN: ["logistics-supply-chain", "healthcare-wellness", "professional-services", "ecommerce-retail"],
  MN: ["healthcare-wellness", "financial-services", "hr-recruitment", "professional-services"],
  WI: ["healthcare-wellness", "professional-services", "logistics-supply-chain", "ecommerce-retail"],
  MO: ["healthcare-wellness", "financial-services", "logistics-supply-chain", "hr-recruitment"],
  MD: ["technology-software", "healthcare-wellness", "professional-services", "legal-services"],
  WA_DC: ["legal-services", "professional-services", "technology-software", "media-content"],
  NV: ["ecommerce-retail", "real-estate-proptech", "logistics-supply-chain", "marketing-advertising"],
  OR: ["technology-software", "ecommerce-retail", "marketing-advertising", "media-content"],
  UT: ["technology-software", "real-estate-proptech", "ecommerce-retail", "hr-recruitment"],
  CT: ["financial-services", "healthcare-wellness", "legal-services", "professional-services"],
  KY: ["logistics-supply-chain", "healthcare-wellness", "professional-services", "ecommerce-retail"],
  OK: ["healthcare-wellness", "logistics-supply-chain", "real-estate-proptech", "professional-services"],
  LA: ["logistics-supply-chain", "healthcare-wellness", "professional-services", "real-estate-proptech"],
  SC: ["healthcare-wellness", "logistics-supply-chain", "ecommerce-retail", "hr-recruitment"],
  AL: ["healthcare-wellness", "logistics-supply-chain", "professional-services", "hr-recruitment"],
  IA: ["logistics-supply-chain", "healthcare-wellness", "professional-services", "hr-recruitment"],
  AR: ["healthcare-wellness", "logistics-supply-chain", "ecommerce-retail", "professional-services"],
  MS: ["healthcare-wellness", "logistics-supply-chain", "professional-services", "ecommerce-retail"],
  KS: ["logistics-supply-chain", "healthcare-wellness", "professional-services", "financial-services"],
  NE: ["logistics-supply-chain", "financial-services", "healthcare-wellness", "hr-recruitment"],
  NM: ["healthcare-wellness", "technology-software", "professional-services", "education-edtech"],
  WV: ["healthcare-wellness", "professional-services", "logistics-supply-chain", "education-edtech"],
  ID: ["technology-software", "real-estate-proptech", "ecommerce-retail", "logistics-supply-chain"],
  HI: ["marketing-advertising", "media-content", "ecommerce-retail", "real-estate-proptech"],
  ME: ["healthcare-wellness", "professional-services", "marketing-advertising", "media-content"],
  NH: ["technology-software", "healthcare-wellness", "professional-services", "financial-services"],
  RI: ["healthcare-wellness", "professional-services", "education-edtech", "financial-services"],
  MT: ["healthcare-wellness", "real-estate-proptech", "technology-software", "professional-services"],
  DE: ["financial-services", "legal-services", "healthcare-wellness", "professional-services"],
  SD: ["healthcare-wellness", "financial-services", "logistics-supply-chain", "professional-services"],
  ND: ["logistics-supply-chain", "healthcare-wellness", "professional-services", "financial-services"],
  AK: ["logistics-supply-chain", "healthcare-wellness", "professional-services", "real-estate-proptech"],
  VT: ["healthcare-wellness", "education-edtech", "professional-services", "marketing-advertising"],
  WY: ["logistics-supply-chain", "healthcare-wellness", "real-estate-proptech", "professional-services"],
};

export const DEFAULT_FEATURED_SECTORS = [
  "professional-services",
  "healthcare-wellness",
  "ecommerce-retail",
  "marketing-advertising",
];

export function getFeaturedSectorIds(stateCode: string): string[] {
  return STATE_SECTORS[stateCode] ?? DEFAULT_FEATURED_SECTORS;
}

export const GROWTH_COLORS: Record<GrowthLevel, string> = {
  "Very High": "bg-emerald-100 text-emerald-700 border-emerald-200",
  "High":      "bg-blue-100 text-blue-700 border-blue-200",
  "Growing":   "bg-violet-100 text-violet-700 border-violet-200",
  "Steady":    "bg-amber-100 text-amber-700 border-amber-200",
};

export const GROWTH_DOT: Record<GrowthLevel, string> = {
  "Very High": "bg-emerald-500",
  "High":      "bg-blue-500",
  "Growing":   "bg-violet-500",
  "Steady":    "bg-amber-500",
};

// All US states for the state picker
export const US_STATES = [
  { code: "AL", name: "Alabama" }, { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" }, { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" }, { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" }, { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" }, { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" }, { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" }, { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" }, { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" }, { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" }, { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" }, { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" }, { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" }, { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" }, { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" }, { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" }, { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" }, { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" }, { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" }, { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" }, { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" }, { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" }, { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" }, { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" }, { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" }, { code: "WY", name: "Wyoming" },
  { code: "DC", name: "Washington D.C." },
];

// Lightweight module metadata for Career Compass training path panel
// (avoids importing the full training-curriculum.ts in a client component)
export const TRAINING_MODULE_META: Record<string, { title: string; duration: string; emoji: string; number: number }> = {
  "career-compass-prep":       { title: "AI-Augmented Role Preparation",   duration: "2h 30min", emoji: "🧭", number: 13 },
  "marketing-workflows":       { title: "Marketing & Growth Workflows",     duration: "3h 20min", emoji: "📣", number: 4  },
  "operations-workflows":      { title: "Operations & Project Management",  duration: "2h 45min", emoji: "⚙️", number: 6  },
  "data-impact-measurement":   { title: "Data & Impact Measurement",        duration: "2h 30min", emoji: "📊", number: 9  },
  "hr-people-workflows":       { title: "HR & People Workflows",            duration: "2h 10min", emoji: "👥", number: 7  },
  "legal-compliance-workflows":{ title: "Legal & Compliance Workflows",     duration: "2h 15min", emoji: "⚖️", number: 8  },
  "finance-workflows":         { title: "Finance & Accounting Workflows",   duration: "2h 40min", emoji: "💰", number: 5  },
  "product-technology":        { title: "Product & Technology Workflows",   duration: "2h 30min", emoji: "💻", number: 10 },
  "ai-leadership-strategy":    { title: "AI Leadership & Strategy",         duration: "3h 00min", emoji: "🎯", number: 12 },
};
