import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import ReferralClient from "./ReferralClient";

export default async function ReferralPage() {
  const session = await auth();
  if (!session?.user?.id) redirect("/login");
  const userId = session.user.id;

  // Get user's referral code (auto-generated by DB default)
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { referralCode: true },
  });

  const referralCode = user?.referralCode ?? userId.slice(0, 8);

  // Get all referrals made by this user, join referred user's name
  const referrals = await prisma.referral.findMany({
    where: { referrerId: userId },
    include: {
      referred: { select: { name: true } },
    },
    orderBy: { createdAt: "desc" },
  });

  const referralData = referrals.map((r) => ({
    id: r.id,
    referredName: r.referred?.name ?? null,
    converted: r.converted,
    createdAt: r.createdAt,
  }));

  return <ReferralClient referralCode={referralCode} referrals={referralData} />;
}
